name: build golden image that run on muilt-arch 
on:
  push:
    branches: 
          - SAAS-28
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."192.168.50.11:5000"]
              http = true
      
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: "http://192.168.50.11:5000/"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Golden Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true 
          tags: 192.168.50.20:5000/golden-image:latest 