name: Gitea Backup to samba
on: push
schedule:
  - cron: '0 9 * * 5'  # 5 AM ET (9 AM UTC) every Friday
workflow_dispatch:

jobs:
  backup-gitea:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Nomad CLI
        run: |
          # Define the version of Nomad you are using on your cluster
          NOMAD_VERSION="1.10.5" # <-- **CHANGE THIS to match your actual Nomad version**
          
          echo "Installing Nomad ${NOMAD_VERSION}..."
          
          # Download, unzip, and move the binary to a PATH directory
          wget -q https://releases.hashicorp.com/nomad/${NOMAD_VERSION}/nomad_${NOMAD_VERSION}_linux_amd64.zip -O nomad.zip
          sudo apt-get install -y unzip # Ensure unzip is available
          unzip nomad.zip
          sudo mv nomad /usr/local/bin/
          
          # Verify installation
          nomad version

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y smbclient

      - name: Run Gitea-backup.sh
        run: |
          chmod +x ./gitea-backup.sh
          ./gitea-backup.sh